uploads = []
generated = []

[[outputs]]
id = "2ZlOSBinEr2pO3qGbRIdG"
uri = "file://Document.md"
type = "text"
title = "CrisisConnect — Complete Technical Documentation"

[[outputs]]
id = "Pbw-1cnFwYTJJzkfB-Z3h"
uri = "file://usage.md"
type = "text"
title = "CrisisConnect — Full Usage Guide"
